cachecapacity: 10000
replicate: 64
pathprefix: /_srcache/
local: localhost:3003
peers:
  - url: localhost
    port: 3001
  - url: localhost
    port: 3002
  - url: localhost
    port: 3003
usegrpc: true
